### ISSUE TITLE
Running waveform benchmark script on MacOS raises FileNotFoundError (strace)

### ISSUE THREAD

**Issue by tompollard** [chorus-ai/chorus_waveform#17]
I downloaded an example waveform file (`s40689238.hea` and `s40689238.dat`) from a project on PhysioNet:
https://physionet.org/content/mimic-iv-ecg/1.0/files/p1000/p10000032/s40689238/#files-panel

When trying to run the waveform benchmark script on MacOS using the following command, I receive a `FileNotFoundError`:

```
python waveform_benchmark.py "40689238.hea" "waveform_benchmark.formats.wfdb.WFDBFormat16"
```

```_____________________________________________________________
Format: waveform_benchmark.formats.wfdb.WFDBFormat16
         (WFDB with 16-bit binary storage)
Record: 40689238
         10 seconds x 12 channels
         60000 timepoints, 60000 samples (100.0%)
________________________________________________________________
Traceback (most recent call last):
  File "/Users/tompollard/projects/chorus_waveform/waveform_benchmark/benchmark.py", line 65, in run_benchmarks
  File "/Users/tompollard/projects/chorus_waveform/waveform_benchmark/ioperf.py", line 50, in __enter__
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'strace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tompollard/projects/chorus_waveform/waveform_benchmark.py", line 6, in <module>
  File "/Users/tompollard/projects/chorus_waveform/waveform_benchmark/__main__.py", line 12, in main
  File "/Users/tompollard/projects/chorus_waveform/waveform_benchmark/benchmark.py", line 61, in run_benchmarks
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tempfile.py", line 904, in __exit__
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tempfile.py", line 908, in cleanup
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tempfile.py", line 890, in _rmtree
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 728, in rmtree
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 725, in rmtree
  File "/Users/tompollard/projects/chorus_waveform/waveform_benchmark/ioperf.py", line 112, in _nocache_hook
AttributeError: module 'os' has no attribute 'posix_fadvise'
```

**Comment by tompollard** [comment]
I don't see a simple way of installing strace on MacOS, so possibly the solution is that the benchmark scripts are just not supported on Mac! (either that, or the script needs rewriting to avoid strace when running on Mac).

**Comment by bemoody** [comment]
Yeah.  What things *can* we easily measure on MacOS?  What do you get from
```
import resource
resource.getrusage(resource.RUSAGE_SELF)
```

**Comment by tompollard** [comment]
```
>>> resource.getrusage(resource.RUSAGE_SELF)

resource.struct_rusage(ru_utime=0.027042,
ru_stime=0.014861999999999998,
ru_maxrss=12763136,
ru_ixrss=0,
ru_idrss=0,
ru_isrss=0,
ru_minflt=1267,
ru_majflt=73,
ru_nswap=0,
ru_inblock=0,
ru_oublock=0,
ru_msgsnd=0,
ru_msgrcv=0,
ru_nsignals=0,
ru_nvcsw=16,
ru_nivcsw=30)
```

**Comment by bemoody** [comment]
It shouldn't raise an error anymore (though it still won't report syscall details on Mac.)
