### ISSUE TITLE
Waveform benchmark raises ValueError (sampfrom must be a non-negative integer) because start_time is negative.

### ISSUE THREAD

**Issue by tompollard** [chorus-ai/chorus_waveform#18]
When running the following command on file [s100780919 in the MIMIC-IV-ECG Demo](https://physionet.org/content/mimic-iv-ecg-demo/0.1/files/p10000032/s100780919/#files-panel) I receive a ValueError ("sampfrom must be a non-negative integer"):

```
python waveform_benchmark.py "100780919.hea" "waveform_benchmark.formats.wfdb.WFDBFormat16"
```

Outputs:

```
________________________________________________________________
Format: waveform_benchmark.formats.wfdb.WFDBFormat516
         (WFDB with FLAC compression)
Record: 100780919
         10 seconds x 12 channels
         60000 timepoints, 60000 samples (100.0%)
________________________________________________________________
Output size:    28 KiB (3.82 bits/sample)
Time to output: 0 sec
________________________________________________________________
Read performance (median of N trials):
 #seek  #read      KiB      sec     [N]
     0     -1       40   0.0053  [1268] read 1 x 10s, all channels
Traceback (most recent call last):
  File "/home/tpollard/projects/chorus_waveform/waveform_benchmark.py", line 6, in <module>
    waveform_benchmark.__main__.main()
  File "/home/tpollard/projects/chorus_waveform/waveform_benchmark/__main__.py", line 12, in main
    run_benchmarks(input_record=opts.input_record,
  File "/home/tpollard/projects/chorus_waveform/waveform_benchmark/benchmark.py", line 89, in run_benchmarks
    fmt().read_waveforms(path, t0, t1, all_channels)
  File "/home/tpollard/projects/chorus_waveform/waveform_benchmark/formats/wfdb.py", line 84, in read_waveforms
    record = wfdb.rdrecord(path, sampfrom=start_frame, sampto=end_frame,
  File "/home/tpollard/miniconda3/envs/physionet/lib/python3.10/site-packages/wfdb/io/record.py", line 2087, in rdrecord
    record.check_read_inputs(
  File "/home/tpollard/miniconda3/envs/physionet/lib/python3.10/site-packages/wfdb/io/record.py", line 620, in check_read_inputs
    raise ValueError("sampfrom must be a non-negative integer")
```

The problem seems to be with the following chunk in the final iteration of `TEST_BLOCK_LENGTHS`:

https://github.com/chorus-ai/chorus_waveform/blob/f1c1352e3b1968a2851447252caa15c251da5641/waveform_benchmark/benchmark.py#L81-L90

`TEST_BLOCK_LENGTHS` contains `[[10.0, 1], [500, 5], [50, 50], [5, 500]]`.

When `t0` is passed to `fmt().read_waveforms(path, t0, t1, all_channels)` it is a negative number: 

total_length = 10
block_length = 500

so `r.random() * (total_length - block_length)` ends up being negative (i.e. a negative record `start_frame`).

**Comment by tompollard** [comment]
> Ah yes. Well, you're asking how long it takes to read 500 seconds of a record that's only 10 seconds long - doesn't make much sense ;) 

@bemoody Maybe `TEST_BLOCK_LENGTHS` could be passed as an argument? (or I guess minimum signal length just needs to be defined in the docs)
