### ISSUE TITLE
DICOM format - KeyError: 'PLETH'

### ISSUE THREAD

**Issue by briangow** [chorus-ai/chorus_waveform#75]
The DICOM format set the IOD based on the channel names. It has an entry for `Pleth` but not `PLETH`. We need to either add `PLETH` or move towards using case insensitive matching. Here is an example of the error:

```
./waveform_benchmark.py -r /home/briangow/chorus/data/mimic_iii/30/3033467/3033467 -f waveform_benchmark.formats.dicom.DICOMHighBitsChunked
________________________________________________________________
Format: waveform_benchmark.formats.dicom.DICOMHighBitsChunked
Record: /home/briangow/chorus/data/mimic_iii/30/3033467/3033467
         39540 seconds x 3 channels
         14827500 timepoints, 14786000 samples (99.7%)
________________________________________________________________
Channel summary information:
 signal       fs(Hz)     Bit resolution       Channel length(s)   
 PLETH        125.00     0.00392(NU)          39507               
 II           125.00     0.00787(mV)          39428               
 V            125.00     0.00787(mV)          39353               
________________________________________________________________
Traceback (most recent call last):
  File "/home/briangow/chorus/repos/chorus_waveform/./waveform_benchmark.py", line 6, in <module>
    waveform_benchmark.__main__.main()
  File "/home/briangow/chorus/repos/chorus_waveform/waveform_benchmark/__main__.py", line 122, in main
    run_benchmarks(input_record=opts.input_record,
  File "/home/briangow/chorus/repos/chorus_waveform/waveform_benchmark/benchmark.py", line 114, in run_benchmarks
    fmt().write_waveforms(path, waveforms)
  File "/home/briangow/chorus/repos/chorus_waveform/waveform_benchmark/formats/dicom.py", line 472, in write_waveforms
    channel_table = self.create_channel_table(waveforms)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/briangow/chorus/repos/chorus_waveform/waveform_benchmark/formats/dicom.py", line 165, in create_channel_table
    iod = CHANNEL_TO_DICOM_IOD[channel]
          ~~~~~~~~~~
```~~~~~~~~~~^^^^^^^^^
KeyError: 'PLETH'

**Comment by tcpan** [comment]
Fixed on format-dicom branch.  Channel names internally are converted to uppercase.  The written DICOM files use the original channel name.   On reading, the requested channel names are internally converted to uppercase for channel name matching; the output uses the channel name in function call and may have different cases than what's in the DICOM file.

**Comment by briangow** [comment]
Fixed by https://github.com/chorus-ai/chorus_waveform/pull/77
