### ISSUE TITLE
DICOM Format - IndexError: too many indices for array

### ISSUE THREAD

**Issue by briangow** [chorus-ai/chorus_waveform#76]
I'm getting an `IndexError` when running this file using the `DICOMHighBits` and `DICOMLowBits` formats:

```
./waveform_benchmark.py -r /home/briangow/chorus/data/mimic_iv/waves/p115/p11596691/86130599/86130599 -f waveform_benchmark.formats.dicom.DICOMHighBits
________________________________________________________________
Format: waveform_benchmark.formats.dicom.DICOMHighBits
Record: /home/briangow/chorus/data/mimic_iv/waves/p115/p11596691/86130599/86130599
         172702 seconds x 5 channels
         161836800 timepoints, 160764160 samples (99.3%)
________________________________________________________________
Channel summary information:
 signal       fs(Hz)     Bit resolution       Channel length(s)   
 II           249.89     0.005(mV)            172287              
 V            249.89     0.005(mV)            172287              
 aVR          249.89     0.005(mV)            172287              
 Pleth        124.94     0.000244(NU)         166816              
 Resp         62.47      0.000485(Ohm)        172282              
________________________________________________________________
Output size:    566274 KiB (28.86 bits/sample)
Time to output: 7 sec
________________________________________________________________
Fidelity check:

Chunk		 Numeric Samples		  NaN Samples
	# Errors  /  Total	  % Eq  	NaN Values Match
Signal: II
  0  	         0/  35632704	100.000		    Y (5056)    
  1  	         0/   7413248	100.000		    Y (1792)    
Signal: V
  0  	         0/  35632704	100.000		    Y (5056)    
  1  	         0/   7413248	100.000		    Y (1792)    
Signal: aVR
  0  	         0/  35632704	100.000		    Y (5056)    
  1  	         0/   7413248	100.000		    Y (1792)    
Signal: Pleth
  0  	         0/  14615040	100.000		     Y (0)      
  1  	         0/    136320	100.000		     Y (0)      
  2  	         0/   3002880	100.000		     Y (0)      
  3  	         0/   3088640	100.000		     Y (0)      
Signal: Resp
  0  	         0/   3134400	100.000		     Y (0)      
  1  	         0/   5774720	100.000		     Y (0)      
Traceback (most recent call last):
  File "/home/briangow/chorus/repos/chorus_waveform/./waveform_benchmark.py", line 6, in <module>
    waveform_benchmark.__main__.main()
  File "/home/briangow/chorus/repos/chorus_waveform/waveform_benchmark/__main__.py", line 122, in main
    run_benchmarks(input_record=opts.input_record,
  File "/home/briangow/chorus/repos/chorus_waveform/waveform_benchmark/benchmark.py", line 157, in run_benchmarks
    filedata = fmt().read_waveforms(path, st, et, [channel])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/briangow/chorus/repos/chorus_waveform/waveform_benchmark/formats/dicom.py", line 719, in read_waveforms
    output[channel][target_start:target_end] = arrs[group_idx][channel_idx, 0:nsamps]
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by briangow** [comment]
@tcpan , I just took a look at this. When the error occurs at line 724:

`output[channel][target_start:target_end] = arrs[group_idx][channel_idx, 0:nsamps]`

`arrs` is empty. This may be because, at `arrs[group_idx] = dcm_reader.get_multiplex_array(fobj, item, start_offset, end_offset, as_raw = False)` we have:
```
start_offset
0
end_offset
0
```
even though `start_time` and `end_time` seem valid. 

It seems like this could be occurring due to differences between `start_time` and `stime`:
```
stime = cast(float, item[0x0099, 0x1001].value)
start_time
143028.6926247549
stime
'167758.9339309'
```

**Comment by tcpan** [comment]
is it possible to check in p115?

**Comment by briangow** [comment]
@tcpan , sure, I've added p115 to the data folder

**Comment by tcpan** [comment]
okay, I see the issue.   the specific dicom file has time range 
167758.9339309 172701.9088

The read operation is requesting the time range 143028.6926247549 167758.9339309296

The end time of the requested block is 0.0000000296 after the start time of the dicom time range.  

I will make the changes to address this case tonight

**Comment by tcpan** [comment]
fixed and tested with p115.   checked in to format-dicom branch.  pull request to come

**Comment by briangow** [comment]
Fixed by https://github.com/chorus-ai/chorus_waveform/pull/77
